### ISSUE TITLE
Docker Pull Failed

### ISSUE THREAD

**Issue by zamtin2021** [jamiesage123/idrac-ipmi-fan-controller#2]
Attempting to pull the image

jamiesage123/idrac_ipmi_fan_controller:latest

Fails due to being restricted or image not present. 

Error returned is   "Error response from daemon: pull access denied for jamiesage123/idrac_ipmi_fan_controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

**Comment by jamiesage123** [comment]
Hey

Looks like I put the wrong docker image repo in the read me, it should be ` jamiesage123/idrac-ipmi-fan-controller` (dashes instead of underscores); this has been corrected

This is the docker command using the correct image:

```
docker run -d \
  --name iDRAC_IPMI_fan_controller \
  --restart=unless-stopped \
  -e IDRAC_HOST=<iDRAC host> \
  -e IDRAC_USERNAME=<iDRAC username> \
  -e IDRAC_PASSWORD=<iDRAC password> \
  -e TEMP_RANGES=<pipe seperated list of temp ranges> \
  jamiesage123/idrac-ipmi-fan-controller:latest
```

Thank you for brining this to my attention

**Comment by zamtin2021** [comment]
Ah ha,  Thanks a ton!


Regards,

Jeff Arms
